language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
notifications:
  email:
      - carrollb1611@gmail.com
    on_success: [always] # default: change
    on_failure: [always] # default: always
